# 🚀 Master NumPy – The Foundation of Data Science & Machine Learning! 🧮 BY: Aniket Sharma

### What are Python modules and packages?
Modular programming refers to the process of breaking a large, unwieldy programming task into separate, smaller, more manageable subtasks or modules. Individual modules can then be cobbled together like building blocks to create a larger application.

*  <u>Simplicity</u>: Rather than focusing on the entire problem at hand, a module typically focuses on one relatively small portion of the problem. If you’re working on a single module, you’ll have a smaller problem domain to wrap your head around. This makes development easier and less error-prone.
   
* <u>Maintainability</u>: Modules are typically designed so that they enforce logical boundaries between different problem domains. If modules are written in a way that minimizes interdependency, there is decreased likelihood that modifications to a single module will have an impact on other parts of the program. (You may even be able to make changes to a module without having any knowledge of the application outside that module.) This makes it more viable for a team of many programmers to work collaboratively on a large applicatioode.
* <u>Reusability</u>: Functionality defined in a single module can be easily reused (through an appropriately defined interface) by other parts of the application. This eliminates the need to duplicate code.e.

### <b> Functions, modules and packages are all constructs in Python that promote code modularization. <b>

## <b> Python Modules: Overview </b>

*  Modules are the pre-defined files that contain the python codes which depict the basic functionalities of class, methods, variables, etc. It consists of different functions, classes in a group of files inside a directory. Modules can also be termed as Libraries. These are basically the pre-defined methods that can be used to make the code more efficient and reduce redundancy.

*  Modules bind the code and reduce the repetitions of functions frequently used in the code. Thus, it makes the code much clear and easy to understand.

*  A module’s contents are accessed with the <code>import</code> statement.

*  A <b>library</b> is a collection of modules, but the terms are often used interchangeably, especially since many libraries only consist of a single module, so don’t worry if you mix them.

### Examples of some popular Python modules are :

*  os
*  math
*  time
*  matplotlib

### <b> One such library in Python is NumPy </b> 
<img src="Numpy.png">

# Numpy
 **NumPy** is a Python package. It stands for **'Numerical Python'**. It is a library consisting of multidimensional array objects and a collection of routines for processing of array. The NumPy package is the workhorse of data analysis, machine learning, and scientific computing in the python ecosystem. It vastly simplifies manipulating and crunching vectors and matrices. Some of python’s leading package rely on NumPy as a fundamental piece of their infrastructure (examples include scikit-learn, SciPy, pandas, and tensorflow). Beyond the ability to slice and dice numeric data, mastering numpy will give you an edge when dealing and debugging with advanced usecases in these libraries. 

### How to install Numpy

In [ ]:
!pip install numpy

### Check Version of Numpy

In [1]:
import numpy as np
print(np.__version__)

1.26.4


<img src="import.png">

### Numpy Array

In [3]:
x=np.array([1,2,3])
print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


<img src="array.png">

### From List

In [11]:
y=[1,2,3,4,5]
print(y)
print(type(y))
x=np.array(y)
print(x)
print(type(x))

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


### Dimension of Arary

In [13]:
arr=np.array(42)
print(arr)

42


##### To check the dimension of the array we have to use method name "ndim"

In [15]:
print(arr.ndim)

0


### 1-Dimension Array:
#### An array that has 0-d array as its elements.

In [17]:
arr1=np.array([1,2,3,4])
print(arr1)
print(arr1.ndim)

[1 2 3 4]
1


<img src="array.png">

### 2-Dimension Array:
#### An array that has 1-d array as its elements.
<img src="2d.png">

In [19]:
arr2=np.array([[1,2],[3,4]])
print(arr2)
print(arr2.ndim)

[[1 2]
 [3 4]]
2


### 3-Dimension Array:
#### An array that has 2-d array as its elements.
<img src="3d.png">

In [53]:
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3)
print(arr3.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


### Higher Dimension Array:
#### Array can have any number of dimension.
##### we can define the dimension of array by using method "ndmin".

In [43]:
arr4=np.array([1,2,3,4,5,6],ndmin=7)
print(arr4)

[[[[[[[1 2 3 4 5 6]]]]]]]


### Array Indexing:
#### 1-d Array

In [46]:
arr1=np.array([1,2,3,4])
print(arr1[-1])
print(arr1[2])

4
3


#### 2-d array

In [49]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2[0,1])
print(arr2[2,1])

2
8


#### 3-d array

In [53]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3[0,1,2])

6


### Slicing in 1-d Array
<img src="slicing.png">

In [55]:
arr1=np.array([1,2,3,4,5,6,7,8,9])
print(arr1[1:5])

[2 3 4 5]


In [57]:
print(arr1[-3:-1])

[7 8]


In [59]:
print(arr1[1:5:2])

[2 4]


In [61]:
print(arr1[::2])

[1 3 5 7 9]


## Slicing in 2-d array
<img src="slicing2d.png">

In [5]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2[0,1:4])

[2 3 4]


In [66]:
print(arr2[0:2,2])

[3 8]


In [68]:
print(arr2[0:2,1:4])

[[2 3 4]
 [7 8 9]]


### Slicing in 3-d array:
<img src="3ds.jpg">

In [75]:
y=np.arange(27).reshape(3,3,3)
print(y)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [77]:
print(y[0])

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [79]:
print(y[1,:,:])

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [81]:
print(y[2,0,1])

19


In [83]:
print(y[::1,:,:])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [85]:
print(y[1:3,1:3,1:3])

[[[13 14]
  [16 17]]

 [[22 23]
  [25 26]]]


### Different Way to Create Numpy Array:
<img src="ways.png">

#### np.zeros() is a function in NumPy that creates a new array filled with zeros.

In [90]:
a=np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


#### np.ones() is a function in NumPy that creates a new array filled with ones.

In [92]:
b=np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### np.full() is a function in NumPy used to create a new array of a specified shape and fill it with a constant value.

In [7]:
c=np.full((2,2),3)
print(c)

[[3 3]
 [3 3]]


#### np.eye(n,m) is used to create an identity matrix or a 2-D array with ones on the diagonal and zeros elsewhere.

In [9]:
d=np.eye(3,3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### np.diag is a function used to either:

1. Extract the diagonal from a 2D array (matrix), or

2. Create a diagonal matrix from a 1D array.

In [98]:
e=np.diag((3,2,8))
print(e)

[[3 0 0]
 [0 2 0]
 [0 0 8]]


In [90]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

diagonal = np.diag(a)
print(diagonal)

[1 5 9]


#### np.arange(start, stop, step):This function is used to create evenly spaced values within a given range.

In [13]:
f=np.arange(1,10,2)
print(f)

[1 3 5 7 9]


#### np.linspace() is a function in NumPy used to create an array of evenly spaced numbers over a specified interval.

In [89]:
# linespace(start, stop, num)
g=np.linspace(1., 4., 6)
print(g)

[1.  1.6 2.2 2.8 3.4 4. ]


#### Generate Random Numbers

In [15]:
# Random float in [0.0, 1.0)
print(np.random.rand())         # single float
print(np.random.rand(2, 3))     # 2x3 array of random floats

0.5906683554410271
[[0.84772997 0.02435185 0.36192685]
 [0.52875265 0.21593784 0.90493009]]


In [24]:
# Random integers
print(np.random.randint(1, 10))# single int from 1 to 9
print("-----------------------")
print(np.random.randint(1, 10, size=5))  # array of 5 random ints
print("-----------------------")
print(np.random.randint(20, 45,(2,3)))

4
9
-----------------------
[7 8 5 2 9]
-----------------------
[[38 38 21]
 [30 39 25]]


### To check the data type of array: dtype

In [103]:
x=np.array((1,2,3,4,5,6,7))
print(x)
print(x.dtype)

[1 2 3 4 5 6 7]
int32


In [105]:
z=np.array(["Apple","Banana","Cherry"])
print(z)
print(z.dtype)

['Apple' 'Banana' 'Cherry']
<U6


In [3]:
z=np.array([2.3,5.7,9.6])
print(z)
print(z.dtype)

[2.3 5.7 9.6]
float64


### How can we define the datatype of array : dtype

In [5]:
t=np.array([123,3,4,5,6,7],dtype="f")
print(t)

[123.   3.   4.   5.   6.   7.]


### How can we change the datatype of existing array: astype

In [7]:
d=np.array([1.6,2.7,3.6,4.1])
print(d)
print(d.dtype)
newarr=d.astype("i")
print(newarr)
print(newarr.dtype)

[1.6 2.7 3.6 4.1]
float64
[1 2 3 4]
int32


### Difference between copy and view:

### 🔁 Copy
A copy creates a new array object with its own separate data.

Changes made to the copy do not affect the original array.

### 👀 View
A view is a shallow copy: it’s a new array object that shares the same data as the original.

Changes made to the view affect the original array (and vice versa).

In [11]:
original = np.array([1,2,3,4,5,6])
print(original)
copy=original.copy()
print(copy)
copy[0]=100
print(copy)
print(original)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[100   2   3   4   5   6]
[1 2 3 4 5 6]


In [15]:
original1 = np.array([1,2,3,4,5,6])
print(original1)
view=original1.view()
print(view)
view[0]=32
print(view)
print(original1)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[32  2  3  4  5  6]
[32  2  3  4  5  6]


In [17]:
arr8=np.array([1,2,3,4,5,6])
e=arr8.copy()
f=arr8.view()
print(e.base)
print(f.base)

None
[1 2 3 4 5 6]


### Shape: The shape of an array is the number of elements in each dimensions.

In [19]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [21]:
crr=np.array([1,2,3,4],ndmin=6)
print(crr)
print(crr.shape)

[[[[[[1 2 3 4]]]]]]
(1, 1, 1, 1, 1, 4)


### Reshaping : Means chage the shape of the array.
<img src="reshape.png">

In [26]:
drr=np.array([1,2,3,4,5,6,7,8])
print(drr)

[1 2 3 4 5 6 7 8]


In [28]:
newarr=drr.reshape(2,2,2)

In [30]:
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [32]:
arr2=np.array([[1,2,3],[5,6,7],[8,9,10]])
print(arr2.shape)

(3, 3)


In [136]:
print(arr2)

[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]]


In [34]:
newarr1=arr2.reshape(-1)
print(newarr1)

[ 1  2  3  5  6  7  8  9 10]


### Traversing of elements of array:

In [141]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [143]:
for i in arr:
    print(i)

1
2
3
4


In [145]:
arr2=np.array([[1,2,3],[4,5,6]])
for i in arr2:
    for j in i:
        print(j)

1
2
3
4
5
6


In [147]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
sum=0
for x in np.nditer(arr3):
    sum+=x
print(sum)

78


In [32]:
for x in np.nditer(arr3):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


### Joinng of Two array:

In [151]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr_1=arr1+arr2
print(arr_1)

[5 7 9]


In [153]:
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


### Splitting of Array:

In [6]:
arr=np.array([1,2,3,4,5,6,7])
newarr=np.array_split(arr,10)
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7]), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32)]


### Searching of array:

In [8]:
arr=np.array([1,2,3,4,5,6])
x=np.where(arr==6)
print(x)

(array([5], dtype=int64),)


In [12]:
arr3=np.array([[[1,2,3],[4,5,8]],[[7,8,9],[10,11,12]]])
y=np.where(arr3==8)
print(y)

(array([0, 1], dtype=int64), array([1, 0], dtype=int64), array([2, 1], dtype=int64))


### Sorting of Array:

In [164]:
arr=np.array([3,6,9,1,0,45])
print(np.sort(arr))

[ 0  1  3  6  9 45]


### Array Manipulation 
#### 1 Transpose:
<img src="transpose.png">

In [14]:
a=np.array(np.random.randint(10,45,(2,3,6)))
print(a)

[[[12 37 10 34 19 17]
  [27 24 15 31 40 33]
  [24 42 22 25 28 12]]

 [[10 11 38 18 16 14]
  [43 41 13 15 19 39]
  [25 41 30 35 44 35]]]


In [169]:
x=np.transpose(a)
print(x)
print(x.shape)

[[[28 26]
  [39 11]
  [33 28]]

 [[12 20]
  [36 33]
  [31 27]]

 [[34 13]
  [32 15]
  [31 14]]

 [[14 31]
  [21 17]
  [36 16]]

 [[27 41]
  [42 17]
  [31 36]]

 [[26 24]
  [28 34]
  [42 32]]]
(6, 3, 2)


In [171]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [173]:
y=np.transpose(b)
print(y)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


### 2. Insert: It insert values into an array at specific position.
#### np.insert(array,index,values,axis)

In [176]:
a=np.array([1,2,3])
print(a)
newarr=np.insert(a,2,100,axis=0)
print(newarr)

[1 2 3]
[  1   2 100   3]


In [178]:
a2=np.array([[1,2],[3,4]])
print(a2)

[[1 2]
 [3 4]]


In [180]:
x=np.insert(a2,1,24,axis=0)
print(x)

[[ 1  2]
 [24 24]
 [ 3  4]]


In [182]:
x=np.insert(a2,1,24,axis=1)
print(x)

[[ 1 24  2]
 [ 3 24  4]]


### 3. Append:
#### np.append(array,values,axis)

In [185]:
a=np.array([1,2,3])
newarr=np.append(a,[4,5],axis=0)
print(newarr)

[1 2 3 4 5]


In [187]:
a2=np.array([[1,2],[3,4]])
print(a2)

[[1 2]
 [3 4]]


In [189]:
newarr2=np.append(a2,[[5,6]],axis=0)
print(newarr2)

[[1 2]
 [3 4]
 [5 6]]


### 3. np.delete(arr,obj,axis)

In [193]:
arr=np.array([1,2,3,4,5])
result=np.delete(arr,[1,3])
print(result)

[1 3 5]


In [195]:
arr=np.array([[1,2,4],[4,5,6],[7,8,9]])
result=np.delete(arr,1,axis=0)
print(result)

[[1 2 4]
 [7 8 9]]


In [197]:
arr=np.random.randint(2,6,(2,3,3))
print(arr)

[[[3 2 4]
  [2 5 5]
  [2 2 3]]

 [[5 2 4]
  [4 3 5]
  [2 2 2]]]


In [199]:
r=np.delete(arr,1,axis=0)
print(r)

[[[3 2 4]
  [2 5 5]
  [2 2 3]]]


In [201]:
r1=np.delete(arr,(0,2),axis=1)
print(r1)

[[[2 5 5]]

 [[4 3 5]]]


In [203]:
r3=np.delete(arr,(0,1),axis=2)

In [205]:
print(r3)

[[[4]
  [5]
  [3]]

 [[4]
  [5]
  [2]]]


### Basic Operations & Functions
#### 1. np.add(array1,array2):

In [210]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])
result=np.add(array1,array2)
print(result)

[5 7 9]


### Broadcasting with scalar:

In [213]:
array=np.array([[1,2],[3,4]])
a=10
result=np.add(array,a)
print(result)

[[11 12]
 [13 14]]


### 2. np.subtract(array1,array2):

In [219]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])
result1=np.subtract(array2,array1)
print(result1)

[3 3 3]


### 3. np.multiply(array1,array2):

In [221]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])
result2=np.multiply(array1,array2)
print(result2)

[ 4 10 18]


### 4. np.divide(array1,array2):

In [224]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])
result3=np.divide(array2,array1)
print(result3)

[4.  2.5 2. ]


### 5. Remainder Operator %

In [ ]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])
result=array2%array1
print(result)

### NumPy - Statistical Functions :-

#### numpy.amin() and numpy.amax()

These functions return the minimum and the maximum value from 
the elements in the given array along the specified axis.

In [229]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 

print('Our array is:' )
print(a) 

Our array is:
[[3 7 5]
 [8 4 3]
 [2 4 9]]


In [231]:
print(np.amin(a))

2


In [233]:
print(np.amin(a,axis=1)) # axis=1 row wise

[3 3 2]


In [235]:
print(np.amin(a,axis=0)) # axis=0 column wise

[2 4 3]


In [237]:
print(np.amax(a))

9


In [239]:
print(np.amax(a, axis = 0)) # axis=0 column wise

[8 7 9]


In [241]:
print(np.amax(a, axis = 1)) # axis=1 row wise

[7 8 9]


In [243]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(np.amin(arr))
print(np.amax(arr))
print("-------------")
print(np.amin(arr,axis=0))
print(np.amax(arr,axis=0))
print("-------------")
print(np.amin(arr,axis=1))
print(np.amax(arr,axis=1))
print("-------------")
print(np.amin(arr,axis=2))
print(np.amax(arr,axis=2))

1
12
-------------
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
-------------
[[1 2 3]
 [7 8 9]]
[[ 4  5  6]
 [10 11 12]]
-------------
[[ 1  4]
 [ 7 10]]
[[ 3  6]
 [ 9 12]]


### Range :
#### numpy.ptp()

numpy.ptp()functions use to plays an important role in statistics
by finding out Range of given numbers. 

Range = max value – min value.

In [246]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])

In [248]:
print('Our array is:') 
print(a) 

Our array is:
[[3 7 5]
 [8 4 3]
 [2 4 9]]


In [250]:
print('Applying ptp() function:' )
print(np.ptp(a)) 

Applying ptp() function:
7


In [252]:
print(np.ptp(a, axis = 1)) # axis=1 row wise

[4 5 7]


In [254]:
print(np.ptp(a, axis = 0)) # axis=0 column wise

[6 3 6]


### Mean
### numpy.mean()

Compute the arithmetic mean (average) of the given data (array elements) along the specified axis.

numpy.mean(arr, axis = None)

Mean Formula:

Mean=Sum of terms/No. of terms

In [259]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

In [261]:
print('Our array is:') 
print(a)

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [263]:
a.sum() # mean=33/9

33

In [265]:
print(a.sum()/9)

3.6666666666666665


In [267]:
print('Applying mean() function:' )
print(np.mean(a))

Applying mean() function:
3.6666666666666665


In [269]:
print(np.mean(a, axis = 0)) # axis=0 column wise

[2.66666667 3.66666667 4.66666667]


In [271]:
print(np.mean(a, axis = 1)) # axis=1 row wise

[2. 4. 5.]


### Median
### numpy.median()

Compute the median of the given data (array elements) along the specified axis.

numpy.median(arr, axis = None)

Median Formula ={(n+1)/2}th when n is odd

Median Formula ={(n)/2)th}

### Median Formula Example:-
#### List of numbers: 4, 10, 7, 15, 2. Calculate the median.

Solution: Let us arrange the numbers in ascending order.

In ascending order, the numbers are: 2,4,7,10,15

Therefore, calculation of the median will be as follows,

There are a total of 5 numbers. Median is (n+1)/2 th value.

Thus, the Median is (5+1)/2 th value.

Median = 3rd value.

The 3rd value in list 2, 4, 7, 10, 15 is 7.

Median will be –

Thus, the Median is 7.

In [277]:
a = np.array([4,10,7,15,2])
print(np.median(a))

7.0


In [279]:
a = np.array([[30,65,70],[80,95,10],[50,90,60]]) 
# 10,30,50,60,65,70,80,90,95

In [281]:
print('Our array is:') 
print(a)

Our array is:
[[30 65 70]
 [80 95 10]
 [50 90 60]]


In [283]:
print('Applying median() function:') 
print(np.median(a))

Applying median() function:
65.0


In [285]:
print('Applying median() function along axis 0:') 
print(np.median(a, axis = 0)) # axis=0 column wise

Applying median() function along axis 0:
[50. 90. 60.]


In [287]:
print('Applying median() function along axis 1:') 
print(np.median(a, axis = 1)) # axis=1 row wise

Applying median() function along axis 1:
[65. 80. 60.]


# Standard Deviation
## numpy.std()

Compute the standard deviation of the given data (array elements) along the specified axis.

numpy.std(arr, axis = None)

The symbol for Standard Deviation is σ (the Greek letter sigma).

This is the formula for Standard Deviation:
<img src="Standard-Deviation-Formula.png">

In [13]:
# 1D array 
arr =np.array([2,6,5,3,2,3])
  
print("arr : ", arr)  
print("std. deviation of arr : ", np.std(arr)) 

arr :  [2 6 5 3 2 3]
std. deviation of arr :  1.5


In [15]:
# 2D array 
arr =np.array([[2, 2, 2, 2, 2],   
       [15, 6, 27, 8, 2],  
       [23, 2, 54, 1, 2, ],  
       [11, 44, 34, 7, 2]])
arr

array([[ 2,  2,  2,  2,  2],
       [15,  6, 27,  8,  2],
       [23,  2, 54,  1,  2],
       [11, 44, 34,  7,  2]])

In [19]:
print(np.std(arr))  

15.3668474320532


In [21]:
print(np.std(arr, axis = 0)) 

[ 7.56224173 17.68473918 18.59267329  3.04138127  0.        ]


In [23]:
print(np.std(arr, axis = 1)) 

[ 0.          8.7772433  20.53874388 16.40243884]


# Variance :
## numpy.var()
<img src="Variance.jpg">
Compute the variance of the given data (array elements) along the specified axis.

Variance is the average of squared deviations, i.e., mean(abs(x - x.mean())**2).

In other words, the standard deviation is the square root of variance.

numpy.var(arr, axis = None)

In [28]:
# 1D array  
arr =np.array([20, 2, 7, 1, 34])  
  
print("arr : ", arr)  
print("variance of arr : ", np.var(arr))  

arr :  [20  2  7  1 34]
variance of arr :  158.16


In [31]:
# 2D array  
arr =np.array([[2, 2, 2, 2, 2],  
    [15, 6, 27, 8, 2],  
    [23, 2, 54, 1, 2, ],  
    [11, 44, 34, 7, 2]]) 
arr

array([[ 2,  2,  2,  2,  2],
       [15,  6, 27,  8,  2],
       [23,  2, 54,  1,  2],
       [11, 44, 34,  7,  2]])

In [33]:
print(np.var(arr)) 

236.14000000000004


In [35]:
print(np.var(arr, axis = 0))

[ 57.1875 312.75   345.6875   9.25     0.    ]


In [37]:
print(np.var(arr, axis = 1))

[  0.    77.04 421.84 269.04]


## Dot Product


In [40]:
# Vectors
a = np.array([1, 2])
b = np.array([3, 4])
dot_product = np.dot(a, b)  # Or a @ b
print("Dot Product:", dot_product)  # Output: 11

# Matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A)
print(B)
matrix_product = np.dot(A, B)  # Or A @ B
print("Matrix Product:\n", matrix_product)

Dot Product: 11
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Matrix Product:
 [[19 22]
 [43 50]]


In [42]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 3]])
result = np.dot(A, B)
print("Matrix Multiplication:\n", result)

Matrix Multiplication:
 [[ 4  6]
 [10 12]]


## Determinnat

In [10]:
from numpy.linalg import det

A = np.array([[1, 2], [3, 4]])
determinant = det(A)
print("Determinant:", determinant) 

Determinant: -2.0000000000000004


In [12]:
B=np.array([[2,-3,1],[2,0,-1],[1,4,5]])
print(B)
determinant=det(B)
print(determinant)

[[ 2 -3  1]
 [ 2  0 -1]
 [ 1  4  5]]
49.000000000000014


## Inverse

In [50]:
from numpy.linalg import inv

A = np.array([[1, 2], [3, 4]])
inverse = inv(A)
print("Inverse Matrix:\n", inverse)

Inverse Matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


## Solution of Linear Equation

In [14]:
from numpy.linalg import solve

A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = solve(A, b)
print("Solution x:", x)  # Output: [2. 3.]

Solution x: [2. 3.]


### Stacking Arrays: Combines multiple arrays into a single array along different axes.
#### Horizontal (hstack())

In [59]:
a=np.array([1,2,3])
b=np.array([4,5,6])
result = np.hstack((a,b))
print(result)

[1 2 3 4 5 6]


### Vertical (vstack())

In [63]:
a=np.array([1,2,3])
b=np.array([4,5,6])
result = np.vstack((a,b))
print(result)

[[1 2 3]
 [4 5 6]]


### Depth Stack (dstack())

In [66]:
a=np.array([1,2,3])
b=np.array([4,5,6])
result = np.dstack((a,b))
print(result)

[[[1 4]
  [2 5]
  [3 6]]]
